//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sajt.DataSloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blog()
        {
            this.comments = new HashSet<comments>();
        }
    
        public int Id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> picture_id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual picture picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
    }
}
