//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sajt.DataSloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int Id { get; set; }
        public Nullable<int> blog_id { get; set; }
        public string user_id { get; set; }
        public string text { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual blog blog { get; set; }
    }
}
